### ISSUE TITLE
Lib/os todo

### ISSUE THREAD

**Issue by litlighilit** [nimpylib/pylib#16]
- [ ] os.stat(..., following_symlink)
- [ ] os.path.exists & pathlib.Path.exists

**Comment by litlighilit** [comment]
os.name:

  - Changed in version 3.3: On Linux, sys.platform doesn’t contain the major version anymore. It is always 'linux', instead of 'linux2' or 'linux3'. Since older Python versions include the version number, it is recommended to always use the startswith idiom presented above.

  - Changed in version 3.8: On AIX, sys.platform doesn’t contain the major version anymore. It is always 'aix', instead of 'aix5' or 'aix7'. Since older Python versions include the version number, it is recommended to always use the startswith idiom presented above.

**Comment by litlighilit** [comment]
- [x] get/set_hlinhertiable
- [ ] lseek

**Comment by litlighilit** [comment]
- [ ] cpu_count

**Comment by litlighilit** [comment]
## unix_only

- [ ] uname  (ref posix_utils.uname)

**Comment by litlighilit** [comment]
## js support

- [ ] open
- [ ] set_inheritable
- [ ] ...
