### ISSUE TITLE
Lib/timeit todo

### ISSUE THREAD

**Issue by litlighilit** [nimpylib/pylib#32]
- [x] Timer
- [ ] when isMainModule  (cli) EDIT: had to finish as Nim is a compile-lang

---

## Todo after above

- [x] mv timeit.nim n_timeit.nim && touch timeit.nim ...
- [x] append pysince

**Comment by litlighilit** [comment]
- [ ] var default_timer = time.perf_counter
